export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const GET_ALL_BOOTCAMPS_STARTS = 'GET_ALL_BOOTCAMPS_STARTS'
export const GET_ALL_BOOTCAMPS_DONE = 'GET_ALL_BOOTCAMPS_DONE'
export const GET_ALL_BOOTCAMPS_FAILED = 'GET_ALL_BOOTCAMPS_FAILED'